### ISSUE TITLE
SOQL with datetime filter wont run

### ISSUE THREAD

**Issue by PetrNovotnyKurim** [AllanOricil/SOQL-Editor-Issues#10]
SOQL: SELECT COUNT(Id) FROM et4ae5__IndividualEmailResult__c WHERE et4ae5__DateSent__c = 2020-03-17T21:04:32.000+0000
ends with error: 0 Results
MALFORMED_QUERY
et4ae5__DateSent__c = 2020-03-17T21:04:32.000 0000 ^ ERROR at Row:1:Column:106 line 1:106 no viable alternative at character &#39; &#39;

![image](https://user-images.githubusercontent.com/25609840/107142975-adcb5f80-6932-11eb-89e2-02aa2296e536.png)

while in the console executed w/o problems 
![image](https://user-images.githubusercontent.com/25609840/107142970-a0ae7080-6932-11eb-97f8-67e054017533.png)

**Comment by AllanOricil** [comment]
Thank you @PetrNovotnyKurim for showing it. I will fix it today and release a patch.

**Comment by PetrNovotnyKurim** [comment]
wow, that is the response.Go to buy you a coffee, now!

**Comment by AllanOricil** [comment]
@PetrNovotnyKurim The v0.10.3 fixes it. Thank you for sharing it. I was using the wrong encoding function.

![image](https://user-images.githubusercontent.com/55927613/107276258-a4cdb180-6a4a-11eb-9265-bc104beb07a0.png)

Close the issue if the problem as been fixed to you. Thank you again
