### ISSUE TITLE
SOQL with '%' wildcard won't run

### ISSUE THREAD

**Issue by cb0wman** [AllanOricil/SOQL-Editor-Issues#11]
SELECT Name FROM Account WHERE Name LIKE '%somestring%' fails with error:
MALFORMED_QUERY
A query string has to be specified

All variations of where you place the '%' result in failed query execution.

**Comment by AllanOricil** [comment]
Hi @cb0wman 
the v0.10.3 fixes it

![image](https://user-images.githubusercontent.com/55927613/107276055-66d08d80-6a4a-11eb-9080-d17ced28e402.png)
