### ISSUE TITLE
Plugin does not work with Alias(s) that contain a space

### ISSUE THREAD

**Issue by Dhorse** [AllanOricil/SOQL-Editor-Issues#12]
If you attempt to run the plugin with an SFDX alias that is in the form of like "My ORG" it will not connect to it successfully.  Updating the alias to not contain spaces was a valid workaround.

**Comment by AllanOricil** [comment]
@Dhorse could you share the error that happens when you use an org with alias such as "My ORG" and how exactly you fixed it?
