### ISSUE TITLE
Could not get environment value

### ISSUE THREAD

**Issue by caisweet** [AllanOricil/SOQL-Editor-Issues#13]
hi Allan,

the editor cannot get the environment value

![image](https://user-images.githubusercontent.com/13267116/111947653-db521e00-8b18-11eb-8e07-dbf980c48d33.png)

but the values is exists
![image](https://user-images.githubusercontent.com/13267116/111947702-f0c74800-8b18-11eb-844c-d14b92a8a003.png)

my plugin version is v1.0.6

![image](https://user-images.githubusercontent.com/13267116/111947987-5e737400-8b19-11eb-89a8-f8dd47c9676c.png)

thank you!

**Comment by AllanOricil** [comment]
@caisweet is vscode opened in the root of a sfdx project?

**Comment by caisweet** [comment]
> @caisweet is vscode opened in the root of a sfdx project?

Hi @AllanOricil, I think yes

![image](https://user-images.githubusercontent.com/13267116/111962985-fb400c80-8b2d-11eb-82e5-f78cdb5ccc79.png)

**Comment by AllanOricil** [comment]
@caisweet you are right. I'm still trying to understand why it is not picking up the root of our workspaces. I'm also facing the same problem on another computer. Sorry for that. Install the old version in the meantime. And again, sorry for that.

**Comment by caisweet** [comment]
Hi @AllanOricil, thank you for your updates,

also for your information, version 0.10.4 is working fine.

![image](https://user-images.githubusercontent.com/13267116/111973998-0862f880-8b3a-11eb-81e8-160f208e193f.png)

**Comment by AllanOricil** [comment]
@caisweet thank you. I will release a fix later today. And thanks for opening the issue

**Comment by AllanOricil** [comment]
@caisweet I fixed it with 1.0.8. Could you try again and check that the CWD is the sfdx project you have opened. Like this:

![image](https://user-images.githubusercontent.com/55927613/111998825-4cdb9d80-8b14-11eb-97a1-cd1f0b2a19f5.png)

**Comment by caisweet** [comment]
Hi @AllanOricil the 1.0.8 is working fine, also please refer to the CWD of me, thanks!

![image](https://user-images.githubusercontent.com/13267116/111999714-335c4500-8b58-11eb-858e-f36c2b42edc1.png)

**Comment by AllanOricil** [comment]
@caisweet Thank you

**Comment by AllanOricil** [comment]
@caisweet I did not update the instructions on the README yet, but since you helped me, here is a tip, you can add the field with double click if you get tired of drag and drop them.
