### ISSUE TITLE
Cannot read property '--vscode-editor-background' of undefined

### ISSUE THREAD

**Issue by tnayrb03** [AllanOricil/SOQL-Editor-Issues#14]
Starting up the application and receive this error

**Comment by AllanOricil** [comment]
@tnayrb03 could you send pictures and tell me which vscode theme you are using. I also need the extension version. Thanks

**Comment by AllanOricil** [comment]
@tnayrb03 Could you also copy and paste all the content from the soql editor output, like shown below

![image](https://user-images.githubusercontent.com/55927613/112194929-4bd46a00-8c01-11eb-97f2-679ddfb41dee.png)

**Comment by AllanOricil** [comment]
@tnayrb03 if you dont mind, we can also have a chat through skype and you show how the bug happened. Then it will be easier for me to fix it for you

**Comment by tnayrb03** [comment]
@AllanOricil sorry about that i stepped out for a second. Let me get you that information i can also be available in about an hour. My VS Code

Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:57:12.728Z (1 wk ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Mac IOS Big Sur Version 11.2.3

This is what im seeing on the output window.

![2021-03-23_13-54-23](https://user-images.githubusercontent.com/26607824/112202654-9e9d2a00-8bdf-11eb-8b01-22cdc19b85e4.jpg)

**Comment by AllanOricil** [comment]
@tnayrb03 do you have a license? And did you activate it? Did this happen before you activate your license?

**Comment by AllanOricil** [comment]
@tnayrb03 I think I found the problem and I have how to fix it. It is in this line 82 shown in the picture below. From your output, I can see the theme colors were not printed, if I compare with my output. These colors are picked up during the initialization and every time you switch colors. When you open VS Code again with a sfdx project, a new tab will open and close very quickly. This tab is basically getting you current colors, storing it and then once my app starts, it will apply those colors to the app's query editor, going through that line 82.

![image](https://user-images.githubusercontent.com/55927613/112292444-fe9bdb00-8c88-11eb-96b7-7d825f22411c.png)

Could you just close VS Code, and then open it again, wait for the extensions activation message and also wait until the colors appear on the output, and then finally open the extension.

![image](https://user-images.githubusercontent.com/55927613/112293562-30fa0800-8c8a-11eb-92b6-1c4076f12503.png)

If this "fixes" your issue I will release a patch to make the extension to open only after receiving the colors, which I should have done already.

**Comment by tnayrb03** [comment]
I have been able to make it work a few times by letting VS Code fully load!!!
