### ISSUE TITLE
erro ao exportar

### ISSUE THREAD

**Issue by dvnube** [AllanOricil/SOQL-Editor-Issues#15]
2021-03-25 12:14:45 : [POST] /sfdx/export/sourcetree/v50.0
{"soql":"SELECT\n    Id,\n    Name,\n    ShippingState,\n    ShippingStreet,\n    ShippingPostalCode,\n    ShippingCountry,\n    ShippingCity\nFROM\n    Account","username":"test-8wddzdlpnaqy@example.com"}
sfdx force:data:tree:export -q "SELECT Id, Name, ShippingState, ShippingStreet, ShippingPostalCode, ShippingCountry, ShippingCity FROM Account" -u "test-8wddzdlpnaqy@example.com" --apiversion 50.0 -p -d c:\Users\Gamer\Documents\Projetos\Repositório MRV\com_salesforce_mrv\data\sourcetree --json
error: Command failed: sfdx force:data:tree:export -q "SELECT Id, Name, ShippingState, ShippingStreet, ShippingPostalCode, ShippingCountry, ShippingCity FROM Account" -u "test-8wddzdlpnaqy@example.com" --apiversion 50.0 -p -d c:\Users\Gamer\Documents\Projetos\Repositório MRV\com_salesforce_mrv\data\sourcetree --json

stdout:
{
  "status": 1,
  "name": "Error",
  "message": "Unexpected argument: MRV\\com_salesforce_mrv\\data\\sourcetree\nSee more help with --help",
  "exitCode": 1,
  "commandName": "DataTreeExportCommand",
  "stack": "Error: Unexpected argument: MRV\\com_salesforce_mrv\\data\\sourcetree\nSee more help with --help\n    at validateArgs (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\node_modules\\@oclif\\parser\\lib\\validate.js:10:19)\n    at Object.validate (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\node_modules\\@oclif\\parser\\lib\\validate.js:55:5)\n    at Object.parse (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\node_modules\\@oclif\\parser\\lib\\index.js:28:7)\n    at DataTreeExportCommand.parse (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\node_modules\\@oclif\\command\\lib\\command.js:86:41)\n    at DataTreeExportCommand.init (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:196:44)\n    at async DataTreeExportCommand._run (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:80:13)\n    at async Config.runCommand (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\client\\7.91.0-6a6ed69ebe\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async Main.run (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\client\\7.91.0-6a6ed69ebe\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n    at async Main._run (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\client\\7.91.0-6a6ed69ebe\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\n    at async Object.run (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\client\\7.91.0-6a6ed69ebe\\dist\\cli.js:121:21)\nOuter stack:\n    at Function.wrap (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:171:27)\n    at DataTreeExportCommand.catch (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:248:46)\n    at async DataTreeExportCommand._run (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:85:13)\n    at async Config.runCommand (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\client\\7.91.0-6a6ed69ebe\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async Main.run (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\client\\7.91.0-6a6ed69ebe\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n    at async Main._run (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\client\\7.91.0-6a6ed69ebe\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\n    at async Object.run (C:\\Users\\Gamer\\AppData\\Local\\sfdx\\client\\7.91.0-6a6ed69ebe\\dist\\cli.js:121:21)",
  "warnings": []
}

2021-03-25 12:14:49 : {"error":"Could not export as Source Tree"}

**Comment by AllanOricil** [comment]
@dvnube I just released a patch to fix it. Upgrade to 1.0.13 and check if the issue has been fixed. The problem was that the -d flag value was missing quotes. Thanks for that.
