### ISSUE TITLE
Site does not load

### ISSUE THREAD

**Issue by BruceBevens** [AllanOricil/SOQL-Editor-Issues#17]
Salesfrocequeryeditor.com never loads

**Comment by AllanOricil** [comment]
@BruceBevens can you post a print screen, please. Thanks

**Comment by AllanOricil** [comment]
It takes around 2s to load because I have not optimized the build for running outside of vscode yet. But it will load, just clear your cache if you have accessed the website before by pressing "CTRL+F5" or "CTRL+r" if you are on Chrome.

**Comment by AllanOricil** [comment]
@BruceBevens I just deployed a build that loads so much fast

**Comment by BruceBevens** [comment]
Thanks @AllanOricil  It is now loading, i think I was getting a timeout from out network firewall because the response was too slow. Thanks

**Comment by AllanOricil** [comment]
@BruceBevens no problem. Thanks for opening the issue. I hope you like it, share with your colleagues and later leave a review  here https://marketplace.visualstudio.com/items?itemName=allanoricil.salesforce-soql-editor&ssr=false#review-details

**Comment by BruceBevens** [comment]
Thanks, I am going to look at it more after work, We are doing our first salesforce implementation and I am a DBA by trade and love the SOQL options in the API's
