### ISSUE TITLE
Can't use. Forced to sign in or sign up. I'm already signed up. Can't sign in now.

### ISSUE THREAD

**Issue by againausername** [AllanOricil/SOQL-Editor-Issues#18]
I already signed up couple weeks ago. Have been using your product. I enjoy using it. Now I can't use it. Can't sign in. Can't sign up. I already signed up. You say my email is invalid or unverified. How Can I use you product?

**Comment by AllanOricil** [comment]
Hi @againausername could you confirm your e-mail. Im gonna verify what happened.

**Comment by againausername** [comment]
I responded with it in my email to you. I think I never got an email from your product registration/verification system I think when I originally signed up. I was able to use it for all this time.

**Comment by AllanOricil** [comment]
@againausername I did not receive an email from you. Could you send a new one to support@salesforcequeryeditor.com. Thanks

**Comment by againausername** [comment]
This is the email I signed up with and have been using for a couple weeks now. 
t.davison@live.ca

**Comment by AllanOricil** [comment]
@againausername I will send you a new verification link and then you click on it from your email. And later tell me if it worked.

**Comment by AllanOricil** [comment]
@againausername did it work?

**Comment by againausername** [comment]
I've been watching my email for your verification link. Still nothing to click on.

**Comment by againausername** [comment]
Sorry, it was in my junk folder.

**Comment by againausername** [comment]
OK, I clicked the email verification link and I signed in to your SOQL editor requesting to stay signed in. Thank You - for your product and your help.
