### ISSUE TITLE
SFDX.soqlEditor not found

### ISSUE THREAD

**Issue by Uncrasher** [AllanOricil/SOQL-Editor-Issues#2]
Hi,
I installed this sweet tool while a project was open and it worked as described.  Then I switched to a new project and it shows that the tool is installed but when I try to access it I get 
the error, "Command 'SFDX: SOQL Editor' resulted in an error (command 'SFDX.soqlEditor' not found)!

I can see it is installed and I can see the DRIVE icon top right corner of the apex class.  No matter how I try to use it I get the same error.

Thanks - hope to see a solution soon.

Tom

**Comment by Uncrasher** [comment]
Update to the issue I wrote yesterday.  After closing VS code and reopening with the newly created project, then SOQL Editor showed up.  All good now.

**Comment by AllanOricil** [comment]
> Update to the issue I wrote yesterday. After closing VS code and reopening with the newly created project, then SOQL Editor showed up. All good now.

Sorry @Uncrasher for the late response. Thanks for opening the issue. Yes, this happen and it is a bad design implementation that I did for not knowing how the activation events worked. I will fix it. Basically if the Extension throw an exception the user can't try to Activate it again. The only way is to close and open the VSCode like you did :/
I will let this issue opened for now and when I fix it I notify you. Thanks @Uncrasher.

**Comment by AllanOricil** [comment]
@Uncrasher I released v0.3.5 to fix this problem.
