### ISSUE TITLE
Could not get Defaultusername Credentials

### ISSUE THREAD

**Issue by nochum** [AllanOricil/SOQL-Editor-Issues#3]
I'm seeing the following issue

<img width="540" alt="image" src="https://user-images.githubusercontent.com/8621714/97025038-8d16ff80-1525-11eb-968e-e991cee11080.png">

Thanks!

**Comment by AllanOricil** [comment]
Hi @nochum could you run `sfdx force:org:display -u ENVIRONMENT_USERNAME_OR_ALIAS` and paste the output here?

**Comment by nochum** [comment]
![image](https://user-images.githubusercontent.com/8621714/97246546-00de3400-17d4-11eb-96aa-5a5979f92e65.png)

It appears that I have some old org configurations in there somewhere...
![image](https://user-images.githubusercontent.com/8621714/97246839-b6a98280-17d4-11eb-8ff6-124f9b7cf4e4.png)

**Comment by nochum** [comment]
Thanks @AllanOricil I resolved it by removing old expired org configurations from ~/.sfdx. I appreciate the help and the awesome tool!

**Comment by AllanOricil** [comment]
@nochum i was facing this same problem. For some reason sfdx started to emit this error for expired orgs when running the display org command. I think this is a undesired sfdx output, probably a bug from their side. I did the same as you. I went to my `%USERNAME%/.sfdx` and deleted the files for the expired orgs. After that sfdx stopped to emit error messages when running display org. 

If anybody else here find the same problem, please just go to sfdx folder in the root of your username folder and delete the config files for those expired orgs.
