### ISSUE TITLE
Not able to obtain token

### ISSUE THREAD

**Issue by billconvis** [AllanOricil/SOQL-Editor-Issues#4]
Hi Allan,
I just downloaded your extension and bought you a large coffee!
I am not having any luck setting up for the auth token.
Followed all your instructions and just cant get the extension to recognize my default org or name.

I develop on multiple projects so have multiple logins to many orgs - maybe that is an issue.
Thanks
Bill Convis

**Comment by AllanOricil** [comment]
Hi @billconvis. First, thank you for your donation. I really appreciate that.
Now let's try to solve your issue. Could you please run the following command from inside a sfdx project `sfdx force:org:display` and paste a print screen of the result here.  Im not passing the username because I'm expecting you already have a `defaultusername` configured locally for that sfdx project.

**Comment by AllanOricil** [comment]
@billconvis try to post a picture like in  this issue. https://github.com/AllanOricil/SOQL-Editor-Issues/issues/3

For some reason sfdx started to throw an exception "ENOENT SOMETHING..." even when the command works. This is what I'm thinking it is happening to you. If it is the case, you will need to go to `c:\USERNAME\.sfdx` and delete the sfdx file for the org that is throwing the error.

**Comment by AllanOricil** [comment]
@billconvis  I cread an issue in the offical sfdx repo for them o fix what I think is also your problem.

https://github.com/forcedotcom/cli/issues/719

**Comment by zix66** [comment]
Same here :(

**Comment by AllanOricil** [comment]
@zix66  
could you paste a Print Screen like the one below. I need to see the output of the command `sfdx force:org:display` for the `defaultusername` of your sfdx project.

![image](https://user-images.githubusercontent.com/55927613/97866436-d3c5e000-1d03-11eb-866e-14ba427ebc78.png)


If the output of the command has an error message like "ENOENT...." it means sfdx is broken and you have to fix it. 
![image](https://user-images.githubusercontent.com/55927613/97866638-3323f000-1d04-11eb-92e8-8c0f12d8f7c0.png)

To fix this problem you have to go to `c:\USERNAME\.sfdx` and delete the files related to the connections that are broken. For instance, in the image above there are two error messages related to this org connection `nklein-acm-demo.my.salesforce.com`.  You are connected to this org through a username, and this username has a correspondent file inside `c:\USERNAME\.sfdx` which you have to delete. After deleting these files, sfdx stops to throw those Exceptions and the SOQL editor works as expected. Below you can see an image of this directory and the files that I'm talking about. You just need to locate the right file and delete it, even if the connection is still valid :/ 

![image](https://user-images.githubusercontent.com/55927613/97867100-19cf7380-1d05-11eb-94c6-39ccaa0078ba.png)

**Comment by michael-malling** [comment]
Are you accounting for version warnings output by SFDX?

**Comment by AllanOricil** [comment]
@michael-malling could you run `sfdx force:org:display --json`. Your case is different to me. Check if sfdx only outputs the json or if it also outputs an warning, and paste a print screen here please.

**Comment by michael-malling** [comment]
Yep both as its part of the stderr stream:
![image](https://user-images.githubusercontent.com/62958961/97910886-653f4d00-1d18-11eb-8970-b0412bc586df.png)

**Comment by AllanOricil** [comment]
> Yep both as its part of the stderr stream:
> ![image](https://user-images.githubusercontent.com/62958961/97910886-653f4d00-1d18-11eb-8970-b0412bc586df.png)

Yes, I will release a fix for that. Current im doing `if(!error && !stderr) doSomething() `

**Comment by AllanOricil** [comment]
@billconvis @michael-malling @zix66  could you all try v0.7.1, please.

**Comment by michael-malling** [comment]
> @billconvis @michael-malling @zix66 could you all try v0.7.1, please.

Sorry - same error.
![image](https://user-images.githubusercontent.com/62958961/97921623-2e256780-1d29-11eb-98c3-1bebb12940e1.png)

**Comment by AllanOricil** [comment]
> > @billconvis @michael-malling @zix66 could you all try v0.7.1, please.
> 
> Sorry - same error.
> ![image](https://user-images.githubusercontent.com/62958961/97921623-2e256780-1d29-11eb-98c3-1bebb12940e1.png)

I made a small mistake, try again on v0.7.2

**Comment by michael-malling** [comment]
> > > @billconvis @michael-malling @zix66 could you all try v0.7.1, please.
> > 
> > 
> > Sorry - same error.
> > ![image](https://user-images.githubusercontent.com/62958961/97921623-2e256780-1d29-11eb-98c3-1bebb12940e1.png)
> 
> I made a small mistake, try again on v0.7.2. Now Im ignoring the `stderr` for sure, and just parsing `sdtout` to get the access token

Yahtzee!! - works...

**Comment by AllanOricil** [comment]
> > > > @billconvis @michael-malling @zix66 could you all try v0.7.1, please.
> > > 
> > > 
> > > Sorry - same error.
> > > ![image](https://user-images.githubusercontent.com/62958961/97921623-2e256780-1d29-11eb-98c3-1bebb12940e1.png)
> > 
> > 
> > I made a small mistake, try again on v0.7.2. Now Im ignoring the `stderr` for sure, and just parsing `sdtout` to get the access token
> 
> Yahtzee!! - works...

Could you do me a favor and post that image of the warning message being outputed alonside the display result on this [bug](https://github.com/forcedotcom/cli/issues/719) I opened for the sfdx team?

**Comment by michael-malling** [comment]
So not sure this scenario applies to that bug/thread - as its a warning and a valid warning. In the bug you opened, I can see why they should not be showing errors for other Org connections in the display command, but in this case its an global SFDX version warning which is applicable to all commands. Do you disagree?

**Comment by AllanOricil** [comment]
> @AllanOricil So not sure this scenario applies to that bug/thread - as its a warning and a valid warning. In the bug you opened, I can see why they should not be showing errors for other Org connections in the display command, but in this case its an global SFDX version warning which is applicable to all commands. Do you disagree?

@michael-malling It is because those Error messages were also being outputed in the 'stderr' which is really weird, because the command actually returned success. And I also think warning messages should not be displayed because it is not what the user requested. Npm does not display warning messages saying to us to update our npm cli. But you are right, better to leave somewhere else. I think they already discussed it in another issue.

**Comment by zix66** [comment]
Did all mentioned in thread 
♦ version updated
♦ related json deleted
♦ project jason updated
♦ set default user
♦ access token exist
.. still getting error now next 
![Screensh_1](https://user-images.githubusercontent.com/44432865/97948304-d292c280-1d98-11eb-9dc2-5972f1d0e83f.jpg)

**Comment by michael-malling** [comment]
@zix66 - Please post the output from the following command:
`sfdx force:org:display`

**Comment by billconvis** [comment]
When in Visual Studio Code - I Open a New Terminal
Run the command and here is the output
[image: image.png]

After I ran this command - I attempted to launch SOQL Editor and VOILA!! We
are in!!

So - looks like we are working now.
Thanks
Bill Convis
530 277 3769

**Comment by AllanOricil** [comment]
Guys leave your feedback on the Vscode marketplace. It will help others to find the extension.
