### ISSUE TITLE
Request failed with status code 400 - Couldn't get SObjects

### ISSUE THREAD

**Issue by pravin-m** [AllanOricil/SOQL-Editor-Issues#5]
Output Panel Displays : Error: Request failed with status code 400
![image](https://user-images.githubusercontent.com/9262212/101490104-e6c57300-3987-11eb-8162-094c719be5cc.png)

----
Org is Authenticated, default username is set. i am able to open the org from terminal without mentioning the org name.
Executed the command to refresh sobjects and selected all objects but still I get the above issue.

SFDX and VSCode are  upto the latest version as of today
VSCODE :1.51.1
SFDX : sfdx-cli/7.81.0-7b953c80d1 win32-x64 node-v12.18.3

**Comment by AllanOricil** [comment]
Could you post a picture of the Output panel after you receive this message. Like in the image below:

![image](https://user-images.githubusercontent.com/55927613/101547594-64967800-39a2-11eb-9fcb-e2c9f99dc3c5.png)

I also need a print screen showing the extension version you have installed.

![image](https://user-images.githubusercontent.com/55927613/101547794-b17a4e80-39a2-11eb-9e06-a8dc87f8b674.png)

**Comment by pravin-m** [comment]
![image](https://user-images.githubusercontent.com/9262212/101559399-0b9d0300-39e7-11eb-8463-d4a6818e9c39.png)
![image](https://user-images.githubusercontent.com/9262212/101559483-371fed80-39e7-11eb-81f2-6cac6b268f8e.png)

**Comment by pravin-m** [comment]
> Hi @pravin-m Could you post a picture of the Output panel after you receive this message. Like in the image below:
> 
> ![image](https://user-images.githubusercontent.com/55927613/101548023-1f267a80-39a3-11eb-8f43-31e300c542c9.png)
> 
> I also need a print screen showing the extension version you have installed.
> 
> ![image](https://user-images.githubusercontent.com/55927613/101547794-b17a4e80-39a2-11eb-9e06-a8dc87f8b674.png)

Thanks for the reply and attention to this bug, I have posted the screenshots you have requested.

**Comment by AllanOricil** [comment]
Ok, I can't debug with just that haha. I will have to print the entire error object to see what happened. I will release a patch that just prints the entire error object in the output and then we can better understand why your request is not working.

**Comment by pravin-m** [comment]
Thank You AllanOricil, for the patch, i did try various ways to debug the issue, and finally gave up. could be on my vscode end some settings are incorrect.

**Comment by AllanOricil** [comment]
@pravin-m could you try again with the new version?

**Comment by pravin-m** [comment]
yes, will keep you posted. Thanks for the update.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
