### ISSUE TITLE
cannot configu defaultusername

### ISSUE THREAD

**Issue by paololucia74** [AllanOricil/SOQL-Editor-Issues#8]
If I launch sfdx force:config:set defaultusername=me@myorg.com
I obtain "ERROR running config:set:  This directory does not contain a valid Salesforce DX project"
What should I configure? thank you

**Comment by AllanOricil** [comment]
@paololucia74 some sfdx commands must run from inside a sfdx project.  To use the extension you must open vscode using the root of your sfdx project. Like this,

![image](https://user-images.githubusercontent.com/55927613/105630430-0e41a380-5e41-11eb-8609-84845130fa13.png)

**Comment by AllanOricil** [comment]
@paololucia74 Did you make it work?
