### ISSUE TITLE
Could not get Defaultusername

### ISSUE THREAD

**Issue by fbairn** [AllanOricil/SOQL-Editor-Issues#9]
When trying to access the editor I am getting the error "Could not get Defaultusername."

I have version 0.10.2 installed.
SFDX CLI Version 7.84.2

Output
![ErrorLog](https://user-images.githubusercontent.com/2752806/106020366-e9d40a00-6080-11eb-8c97-1ed2dec81dde.png)

Running the sfdx force:org:display provides the following
![command](https://user-images.githubusercontent.com/2752806/106020456-06704200-6081-11eb-809e-2a88bb80e58a.png)

**Comment by AllanOricil** [comment]
@fbairn So it located your username but it could not convert the JSON from the output. Could you share the content of this file `.sfdx/sfdx-config.json`. It is inside the folder `.sfdx` that is the root of your sfdx project, as shown below:

![image](https://user-images.githubusercontent.com/55927613/106172755-1411ee80-618b-11eb-8aa0-59c681bf5b4c.png)

I also need the output of `sfdx force:org:display --json` without the username being covered. You can hide the accessToken and the password.

**Comment by AllanOricil** [comment]
@fbairn I'm closing this as you did not answer back. Thank you.
